- hosts: all
  become: true
  tasks: 
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: Change password of user 'pi' to random string
      ansible.builtin.user:
        name: pi
        password: "{{ lookup('community.general.random_string', length=64) | password_hash('sha512', 'mysecretsalt') }}"
    - name: Disable ssh password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication'
        line: 'PasswordAuthentication no'
    - name: Disable ssh root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        line: 'PermitRootLogin no'
    - name: Set ssh AuthenticationMethods
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: 'AuthenticationMethods publickey'
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
      